# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Required', max_length=50)),
                ('Email', models.EmailField(help_text='Required', max_length=250)),
                ('Mobile', models.IntegerField(help_text='Required', max_length=10)),
                ('Workshop', models.CharField(choices=[('workshop 1', 'Workshop 1'), ('workshop 2', 'Workshop 2'), ('workshop 3', 'Workshop 3'), ('workshop 4', 'Workshop 4')], help_text='Required', max_length=35)),
            ],
        ),
    ]
