# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Workshop',
            field=models.BooleanField(choices=[('workshop 1', 'Workshop 1'), ('workshop 2', 'Workshop 2'), ('workshop 3', 'Workshop 3'), ('workshop 4', 'Workshop 4')], help_text='Required'),
        ),
    ]
