# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0002_auto_20171022_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Workshop',
            field=models.CharField(choices=[('workshop 1', 'Workshop 1'), ('workshop 2', 'Workshop 2'), ('workshop 3', 'Workshop 3'), ('workshop 4', 'Workshop 4')], help_text='Required', max_length=35),
        ),
    ]
