# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0003_auto_20171025_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='details',
            name='Mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='Workshop',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('workshop 1', 'Workshop 1'), ('workshop 2', 'Workshop 2'), ('workshop 3', 'Workshop 3'), ('workshop 4', 'Workshop 4')], max_length=43),
        ),
    ]
